services:
  postgres:
    image: postgres:14.15-alpine3.21
    restart: always
    container_name: postgres-books
    ports:
      - 5432:5432
    volumes:
      - booksdb-v:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=booksdb
    networks:
      - books-n
  jenkins:
    image: jenkins/jenkins:lts
    privileged: true
    user: root
    ports:
      - 8080:8080
      - 50000:50000
    container_name: jenkins-books
    volumes:
      - ./jenkins_compose/jenkins_conf:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - books-n
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
    container_name: zipkin-books
    networks:
      - books-n

networks:
  books-n:
    external: true

volumes:
  booksdb-v:
    external: true
