services:
  postgres-rx:
    image: postgres:14.15-alpine3.21
    restart: always
    container_name: postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=booksdb
