apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloud-config-server-app
  labels:
    app: cloud-config-server-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cloud-config-server-app
  template:
    metadata:
      labels:
        app: cloud-config-server-app
    spec:
      containers:
        - name: cloud-config-server-app
          image: kajtekdocker/config-server:0.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 9955
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"

---
kind: Service
apiVersion: v1
metadata:
  name: cloud-config-server-svc
spec:
  selector:
    app: cloud-config-server-app  
  ports:    
    - port: 80
      targetPort: 9955
