apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service-app
  labels:
    app: inventory-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-service-app
  template:
    metadata:
      labels:
        app: inventory-service-app
    spec:
      containers:
        - name: inventory-service-app
          image: kajtekdocker/books-inventory:0.0.2
          imagePullPolicy: Always
          ports:
            - containerPort: 9091
          resources:
            requests:
              memory: "512Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"

---
kind: Service
apiVersion: v1
metadata:
  name: inventory-service-svc
spec:
  selector:
    app: inventory-service-app
  type: ClusterIP
  ports:    
    - port: 80
      targetPort: 9091
