pipeline {
    agent {
        node {
            label 'docker-book-service-agent'
        }
    }
    triggers {
        pollSCM '*/1 * * * *'
    }

    stages {
        stage('Build') {
            steps {
                script {
                    dir('backend/book-service') {
                        sh './gradlew build -x test'
                    }
                }
            }
        }

        stage('Test') {
            steps {
                script {
                    dir('backend/book-service') {
                        sh './gradlew test'
                    }
                }
            }
        }
    }
}
