pipeline {
    agent {
        node {
            label 'docker-book-service-agent'
        }
    }
    triggers {
        pollSCM '*/1 * * * *'
    }

    dir('backend/book-service') {}
    stages {
        stage('Build') {
            steps {
                script {
                    sh './gradlew build -x test'
                }
            }
        }

        stage('Test') {
            steps {
                script {
                        sh './gradlew test'

                }
            }
        }
    }

}
