pipeline {
    agent {
        node {
            label 'docker-book-service-agent'
        }
    }
    triggers {
        pollSCM '*/1 * * * *'
    }

    stages {
        stage('Build') {
            steps {
                dir('backend/book-service') {
                    sh './gradlew build -x test'
                }
            }
        }

        stage('Test') {
            steps {
                dir('backend/book-service') {
                    sh './gradlew test'
                }
            }
        }
    }
}
