server:
  port: 9091

spring:
  application:
    name: books-inventory
  management:
    tracing:
      enabled: true
  zipkin:
    base-url: http://127.0.0.1:9411/
  config:
    import: configserver:http://localhost:9955/


eureka:
  instance:
    preferIpAddress: true
    hostname: eureka-0
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://eureka-0.eureka.default.svc.cluster.local:8761/eureka